/**
 * Canvas manifest types — neutral data shape that any playground / canvas tool
 * can consume from `pod-test-ui/canvas`.
 *
 * Per-component metadata lives in `src/<dir>/canvas.ts`. The aggregator
 * `src/canvas.ts` is AUTO-GENERATED by `scripts/canvas/sync.mjs` — do not edit
 * it by hand.
 */

export interface CanvasExample {
  label: string;
  props: Record<string, unknown>;
  /**
   * Optional raw JSX/TSX override. When set, playground tools spawn this code
   * verbatim instead of building from props. Use for composite examples that
   * need state hooks (e.g. wired Dropdown with menu items + open state).
   * MUST be a single React component declaration (`function Foo() { ... }`)
   * — Sucrase runtime expects this shape.
   */
  code?: string;
}

export interface CanvasComponent {
  name: string;
  importFrom: string;
  variants: readonly string[];
  sizes: readonly string[];
  defaultProps: Record<string, unknown>;
  examples?: readonly CanvasExample[];
  /**
   * Allowlist of POD token KEYS (without the `--color-` prefix) that this
   * component consumes regardless of variant — e.g. focus ring color used
   * by every variant. Combined with `variantTokens` when filtering.
   */
  tokens?: readonly string[];
  /**
   * Per-variant token allowlist. The panel shows the union of
   * `tokens` (common) + `variantTokens[currentVariant]` (variant-specific).
   * Use this to scope tokens to what each variant ACTUALLY consumes —
   * e.g. Primary uses `accent-*`, Error uses `danger-*`.
   */
  variantTokens?: Record<string, readonly string[]>;
  /**
   * Sub-primitives exported by this component's index.ts that must ALSO
   * be in scope when consumers run composite snippets (function components
   * that reference these names). E.g. Dropdown ships DropdownMenu, DropdownItem,
   * DropdownBadge. Playground runtimes inject all of these into `new Function(...)`
   * scope so composite `code` examples can use them without explicit imports.
   */
  extraScope?: readonly string[];
}

export interface CanvasManifest {
  version: string;
  components: readonly CanvasComponent[];
}
