/**
 * Canvas manifest types — neutral data shape that any playground / canvas tool
 * can consume from `pod-test-ui/canvas`.
 *
 * Per-component metadata lives in `src/<dir>/canvas.ts`. The aggregator
 * `src/canvas.ts` is AUTO-GENERATED by `scripts/canvas/sync.mjs` — do not edit
 * it by hand.
 */

export interface CanvasExample {
  label: string;
  props: Record<string, unknown>;
}

export interface CanvasComponent {
  name: string;
  importFrom: string;
  variants: readonly string[];
  sizes: readonly string[];
  defaultProps: Record<string, unknown>;
  examples?: readonly CanvasExample[];
  /**
   * Allowlist of POD token KEYS (without the `--color-` prefix) that this
   * component consumes regardless of variant — e.g. focus ring color used
   * by every variant. Combined with `variantTokens` when filtering.
   */
  tokens?: readonly string[];
  /**
   * Per-variant token allowlist. The panel shows the union of
   * `tokens` (common) + `variantTokens[currentVariant]` (variant-specific).
   * Use this to scope tokens to what each variant ACTUALLY consumes —
   * e.g. Primary uses `accent-*`, Error uses `danger-*`.
   */
  variantTokens?: Record<string, readonly string[]>;
}

export interface CanvasManifest {
  version: string;
  components: readonly CanvasComponent[];
}
