/* AUTO-GENERATED by scripts/canvas/sync.mjs — DO NOT EDIT.
 * Re-run `node scripts/canvas/sync.mjs` after adding/removing component dirs.
 */
import type { CanvasManifest } from './canvas-types.js';
import { buttonCanvas } from './button/canvas.js';
import { checkboxCanvas } from './checkbox/canvas.js';
import { switchCanvas } from './switch/canvas.js';
import { textInputCanvas } from './text-input/canvas.js';

export * from './canvas-types.js';

export const canvasManifest: CanvasManifest = {
  version: '1',
  components: [
    buttonCanvas,
    checkboxCanvas,
    switchCanvas,
    textInputCanvas,
  ],
};
