/**
 * Canvas manifest types — neutral data shape that any playground / canvas tool
 * can consume from `pod-test-ui/canvas`.
 *
 * Per-component metadata lives in `src/<dir>/canvas.ts`. The aggregator
 * `src/canvas.ts` is AUTO-GENERATED by `scripts/canvas/sync.mjs` — do not edit
 * it by hand.
 */

export interface CanvasExample {
  label: string;
  props: Record<string, unknown>;
}

export interface CanvasComponent {
  name: string;
  importFrom: string;
  variants: readonly string[];
  sizes: readonly string[];
  defaultProps: Record<string, unknown>;
  examples?: readonly CanvasExample[];
}

export interface CanvasManifest {
  version: string;
  components: readonly CanvasComponent[];
}
