import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'badges': 'src/badges/index.ts',
    'button': 'src/button/index.ts',
    'button-group': 'src/button-group/index.ts',
    'chart-tooltip': 'src/chart-tooltip/index.ts',
    'checkbox': 'src/checkbox/index.ts',
    'dashboard-forecast-chart': 'src/dashboard-forecast-chart/index.ts',
    'dashboard-jobs-insights': 'src/dashboard-jobs-insights/index.ts',
    'dashboard-kpis': 'src/dashboard-kpis/index.ts',
    'dashboard-map-budget': 'src/dashboard-map-budget/index.ts',
    'dashboard-skills-insights': 'src/dashboard-skills-insights/index.ts',
    'date-picker': 'src/date-picker/index.ts',
    'day': 'src/day/index.ts',
    'dropdown': 'src/dropdown/index.ts',
    'kpi-card': 'src/kpi-card/index.ts',
    'legend': 'src/legend/index.ts',
    'list-base': 'src/list-base/index.ts',
    'overlay-scroll-area': 'src/overlay-scroll-area/index.ts',
    'progress-bar': 'src/progress-bar/index.ts',
    'progress-bar-base': 'src/progress-bar-base/index.ts',
    'progress-value-bar': 'src/progress-value-bar/index.ts',
    'radio': 'src/radio/index.ts',
    'search-field': 'src/search-field/index.ts',
    'search-input': 'src/search-input/index.ts',
    'segmented-button': 'src/segmented-button/index.ts',
    'switch': 'src/switch/index.ts',
    'tabs': 'src/tabs/index.ts',
    'tag': 'src/tag/index.ts',
    'text-input': 'src/text-input/index.ts',
    'tooltip': 'src/tooltip/index.ts',
    canvas: 'src/canvas.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  splitting: true,
  sourcemap: true,
  minify: false,
  outDir: 'dist',
  external: ['react', 'react-dom'],
});
