import type { ComponentType } from 'react';
import {
  Activity,
  AlignLeft,
  Award,
  BarChart2,
  BellRing,
  CalendarRange,
  CheckSquare,
  ChevronDown,
  ChevronsRight,
  ChevronsUpDown,
  CircleDot,
  CloudUpload,
  Compass,
  Disc,
  FileText,
  FolderTree,
  FormInput,
  Gauge,
  GitCommit,
  Inbox,
  Layers,
  LayoutGrid,
  List,
  ListOrdered,
  Loader2,
  MessageSquare,
  Minus,
  MoreHorizontal,
  MousePointerClick,
  MoveHorizontal,
  Palette,
  Search,
  Sliders,
  SlidersHorizontal,
  Split,
  Square,
  Tag as TagIcon,
  ToggleRight,
  TrendingUp,
  Type,
  User,
  Users,
  Baseline,
  Box,
} from 'lucide-react';

const iconMap: Record<string, ComponentType<{ className?: string }>> = {
  '/components/account-switcher': Users,
  '/components/avatar': User,
  '/components/badge': Award,
  '/components/breadcrumb': ChevronsRight,
  '/components/button': MousePointerClick,
  '/components/chart-tooltip': BarChart2,
  '/components/checkbox': CheckSquare,
  '/components/combobox': ChevronsUpDown,
  '/components/drop-zone': CloudUpload,
  '/components/dropdown': ChevronDown,
  '/components/empty-state': Inbox,
  '/components/file-list': FileText,
  '/components/gantt-bar': CalendarRange,
  '/components/text-input': Type,
  '/components/kpi-card': TrendingUp,
  '/components/legend': ListOrdered,
  '/components/list-base': List,
  '/components/loading-spinner': Loader2,
  '/components/nav-item': Compass,
  '/components/nav-section': FolderTree,
  '/components/pagination': MoreHorizontal,
  '/components/progress-bar': Minus,
  '/components/progress-bar-base': Activity,
  '/components/progress-ring': CircleDot,
  '/components/progress-value-bar': SlidersHorizontal,
  '/components/radio': Disc,
  '/components/search-field': Search,
  '/components/segmented-button': LayoutGrid,
  '/components/separator': Split,
  '/components/skill-level': Gauge,
  '/components/slider': Sliders,
  '/components/switch': ToggleRight,
  '/components/tag': TagIcon,
  '/components/text-area': AlignLeft,
  '/components/text-field': FormInput,
  '/components/timeline': GitCommit,
  '/components/toast': BellRing,
  '/components/tooltip': MessageSquare,
  '/foundations/color': Palette,
  '/foundations/typography': Baseline,
  '/foundations/spacing': MoveHorizontal,
  '/foundations/radius': Square,
  '/foundations/elevation': Layers,
};

export function getComponentIcon(path: string): ComponentType<{ className?: string }> {
  return iconMap[path] ?? Box;
}
